// Generated by CoffeeScript 1.8.0
(function() {
  var Canvas, captcha, luminance, pickRandom;

  Canvas = require('canvas');

  pickRandom = function(items) {
    return items[Math.floor(Math.random() * items.length)];
  };

  luminance = function(hex, lum) {
    return hex.match(/.{1,2}/g).map(function(c) {
      c = parseInt(c, 16) * (1 + lum);
      c = c < 0 ? 0 : c > 255 ? 255 : c;
      c = Math.round(c).toString(16);
      return ("00" + c).substr(c.length);
    }).join('');
  };

  captcha = function(_arg) {
    var background, canvas, cellWidth, char, chars, code, color, ctx, fonts, height, i, length, noise, width, x, y, _color, _i, _j, _k, _ref, _ref1;
    height = _arg.height, width = _arg.width, length = _arg.length, color = _arg.color, background = _arg.background, chars = _arg.chars, fonts = _arg.fonts, noise = _arg.noise;
    chars = (chars || 'abcdefghijklmnopqrstuvwxyz0123456789').match(/.{1}/g);
    if (length == null) {
      length = 4;
    }
    if (width == null) {
      width = 125;
    }
    if (height == null) {
      height = 50;
    }
    if (color == null) {
      color = '#888888';
    }
    _color = color.substr(1);
    if (background == null) {
      background = "#ffffff";
    }
    if (fonts == null) {
      fonts = ['20px sans', '20px arial', 'bold 20px arial', 'italic 20px sans'];
    }
    noise = (noise || 90) * 0.01 - 0.5;
    canvas = new Canvas(width, height);
    ctx = canvas.getContext('2d');
    ctx.fillStyle = background;
    ctx.fillRect(0, 0, width, height);
    ctx.fillStyle = ctx.strokeStyle = color;
    code = '';
    cellWidth = width / length;
    for (i = _i = 0; 0 <= length ? _i < length : _i > length; i = 0 <= length ? ++_i : --_i) {
      char = pickRandom(chars);
      code += char;
      ctx.font = pickRandom(fonts);
      ctx.setTransform(Math.random() * 0.4 + 1, Math.random() * 0.5, Math.random() * 0.5, Math.random() * 0.6 + 1, cellWidth * i + cellWidth * 0.4, height * 0.6);
      ctx.fillStyle = "#" + (luminance(_color, Math.random() * 0.1));
      ctx.fillText(char, 0, 0);
    }
    ctx.globalCompositeOperation = 'lighter';
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    for (x = _j = 0, _ref = Math.ceil(width * 0.5); 0 <= _ref ? _j < _ref : _j > _ref; x = 0 <= _ref ? ++_j : --_j) {
      for (y = _k = 0, _ref1 = Math.ceil(height * 0.5); 0 <= _ref1 ? _k < _ref1 : _k > _ref1; y = 0 <= _ref1 ? ++_k : --_k) {
        if (Math.random() < noise) {
          ctx.fillStyle = "#" + (luminance(_color, Math.random()));
          ctx.fillRect(x * 2, y * 2, 2, 2);
        }
      }
    }
    return {
      canvas: canvas,
      code: code
    };
  };

  exports.captcha = captcha;

  exports.middleware = function(options) {
    return function(req, res) {
      var canvas, code, _ref;
      _ref = captcha(options), canvas = _ref.canvas, code = _ref.code;
      req.session.captcha = code;
      return canvas.toBuffer(function(err, buffer) {
        return res.end(buffer);
      });
    };
  };

}).call(this);
